### ISSUE TITLE
Problem finding .blp and .skin

### ISSUE THREAD

**Issue by DenisDemins** [Mugen87/three-m2loader#17]
Hello, in your example in the test folder I saw that bearmount.m2 is used, I exported all the files with wow.export but threem2loader searches for textures and skins by fileDataID and not by file name. After I looked at bearmount.manifest.json and renamed all the .blp and .skin file names to {fileDataID}.blp everything worked. Is there any way to fix this?

**Comment by Mugen87** [comment]
> Is there any way to fix this?

I'm not aware of a fix without using the actual WoW client database which is not possible for `M2Loader`. The loader can only work with the information embedded in the M2 file and at least for more recent WoW assets you get file data ids for external resources like skin and textures.
